---
title: "Fig. 1d"
output: html_document
author: "Seung J. Kim (skim823@uwo.ca)"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# Load libraries
library(readxl)         # for reading Excel files
library(nnet)           # for multinomial logistic regression
library(dplyr)          # for data manipulation
library(tidyr)          # for handling missing data
library(janitor)        # optional: for cleaning column names

# Read data
metadata <- read_excel("/Users/jk/Documents/Lab2/visium/python_analysis/lambda/metadata_batch_effect.xlsx") %>%
  clean_names()  # makes column names lowercase and underscores

# Check data
str(metadata)
summary(metadata)

# Factor everything
metadata <- metadata %>%
  mutate(
    cond = factor(cond),
    outcome_24m = factor(outcome_24m),
    age = as.numeric(age),
    sex = factor(sex),
    bmi = as.numeric(bmi),
    packyears = as.numeric(packyears),
    fvc = as.numeric(fvc),
    dlco = as.numeric(dlco),
    x6mwd = as.numeric(x6mwd)
  )

# Remove rows with any missing predictor
metadata_complete <- metadata %>%
  drop_na(age, sex, bmi, packyears, fvc, dlco)  


# Fit multinomial logistic regression
# Base reference level is IPF
metadata_complete$cond <- relevel(metadata_complete$cond, ref = "IPF")  
#metadata_complete$outcome_24m <- relevel(metadata_complete$outcome_24m, ref = "ALIVE")
model <- multinom(cond ~ age + sex + bmi + packyears + fvc + dlco , data = metadata_complete)
#model <- multinom(outcome_24m ~ age + sex + bmi + packyears + fvc + dlco , data = metadata_complete)

# View model results
summary(model)

coefs <- summary(model)$coefficients      # matrix: rows = outcomes, cols = predictors
ses <- summary(model)$standard.errors      # same shape


# Calculate z-scores and p-values
z_scores <- coefs / ses
p_values <- 2 * (1 - pnorm(abs(z_scores)))


# Calculate lower and upper CI on log-odds scale
conf_low_logodds <- coefs - 1.96 * ses
conf_high_logodds <- coefs + 1.96 * ses

# Convert matrices to data frames with rownames as 'response'
df_coefs <- as.data.frame(coefs) %>%
  mutate(response = rownames(coefs)) %>%
  pivot_longer(cols = -response, names_to = "term", values_to = "estimate") # wide to long

df_pvals <- as.data.frame(p_values) %>%
  mutate(response = rownames(p_values)) %>%
  pivot_longer(cols = -response, names_to = "term", values_to = "p_value")

# Not using it but still included
df_conf_low <- as.data.frame(conf_low_logodds) %>%
  mutate(response = rownames(conf_low_logodds)) %>%
  pivot_longer(-response, names_to = "term", values_to = "conf.low_logodds")
# Not using it but still included
df_conf_high <- as.data.frame(conf_high_logodds) %>%
  mutate(response = rownames(conf_high_logodds)) %>%
  pivot_longer(-response, names_to = "term", values_to = "conf.high_logodds")


# Join df's into one
results_df <- left_join(df_coefs, df_pvals, by = c("response", "term")) %>%
              left_join(df_conf_high, by = c("response", "term")) %>%
              left_join(df_conf_low, by = c("response","term"))
  




library(broom)

results_df <- results_df %>%
  mutate(odds_ratio = exp(estimate),
         conf.low = exp(conf.low_logodds),
         conf.high = exp(conf.high_logodds),
         sig = p_value < 0.05)  # Instead of exact value

library(ggplot2)
```

```{r}
results_df$response = factor(results_df$response, levels=c("NSIP","CHP","UNC"))
or_plot_cond <- ggplot(results_df %>% filter(term != "(Intercept)"),
       aes(y = term, x = odds_ratio, fill = response, shape = sig)) +
  geom_point(position = position_dodge(width = 0.5), size =6, colour ="black") +
  geom_vline(xintercept = 1, linetype = "dashed") +
  scale_y_discrete(labels = c(
    "age" = "Age",
    "sexM" = "Sex (Male)",
    "bmi" = "BMI",
    "packyears" = "Smoking (Pack-Years)",
    "fvc" = "FVC (% pred.)",
    "dlco" = "DLCO (% pred.)"
    #"x6mwd" = "6MWD"
  ))+
  scale_shape_manual(
    "P < 0.05?",
    values = c(
      "TRUE" = 21,
      "FALSE" = 23
    )
  )+
  scale_fill_manual(values = c(
    "NSIP" = "#dd8452",   # blue
    "CHP" = "#55a868",  # orange
    "UNC" = "#c44e52"    # green
  )) +
  #coord_flip() +
  labs(title = "",
       fill = "Diagnosis",
       shape = '-log p val',
       
       x = "Odds Ratio",
       y = "Predictor") +
  xlim(0,2)+
  #scale_y_log10() +  # Optional: log scale for readability
  theme_bw()+
  theme(
    # grid lines can be controversial, in my field it's not seen often
    panel.grid.minor=element_blank(), 
    panel.grid.major=element_blank(),
    axis.text = element_text(color="black",size=14), # default font size is too small
    axis.text.x = element_text(angle = 30, hjust = 1),
    axis.ticks = element_line(colour="black", linewidth = 1), # just plain old black please
    axis.title = element_text(size=14), # default font size is too small
    legend.title=element_text(size=14, vjust=0.5, hjust=0.5),
    legend.text=element_text(size=14, vjust=0.5, hjust=0),
    plot.margin=unit(c(1,1,1,1),"cm"),
    plot.background=element_rect(fill="transparent", colour=NA),
    panel.border = element_rect(colour="black", linewidth = 1), # I like to draw a crisp border
    panel.background=element_rect(fill="transparent", colour=NA),
    legend.background=element_rect(fill="transparent", colour=NA),
    legend.box.background=element_rect(fill="transparent", colour=NA),
    legend.key=element_rect(fill="transparent", colour=NA),
    legend.position = 'right')+
 guides(
    fill = guide_legend(
      override.aes = list(shape = 21, color = "black", size = 6)
    )
  )

or_plot_cond
```

```{r}
pdf("or_plot_cond.pdf", width = 6, height = 4)
print(or_plot_cond)
dev.off()
```

