---
title: "Fig. 7c"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(glmnet)
library(readr)
library(dplyr)
library(Matrix)
library(pROC)
library(readxl)
library(caret)
library(dplyr)
library(tidyverse)

predicted_meta <- read_csv("/Users/jk/Documents/Lab2/visium/library_to_cond_concat_wo_unc.csv") 

library(caret)
library(dplyr)

mclust_predicted <- read_csv("/Users/jk/Documents/Lab2/visium/python_analysis/cpath/trident/wsi_svs/all_sample_proportions_200px.csv")


mclust_predicted <- mclust_predicted %>%
  mutate(library_id = str_replace_all(library_id, "-", "_")) %>%
  rename(`0` = 'class_0',
         `1` = 'class_1',
         `2` = 'class_2',
         `3` = 'class_3',
         `4` = 'class_4',
         `5` = 'class_5',)
mclust_predicted <- left_join(mclust_predicted, predicted_meta, by = "library_id")
mclust_predicted <- mclust_predicted %>%
  #filter(cond != "UNC")%>%
  mutate(
    cond = recode(cond,
                  "NSIP" = "nonIPF",
                  "CHP"  = "nonIPF")
  ) 

y <- factor(mclust_predicted$cond)
X  <- mclust_predicted %>% dplyr::select( -library_id, -cond) %>% as.matrix()


n <- nrow(X)
classes <- levels(y)
preds <- factor(rep(NA, n), levels = classes)
probs_loocv <- matrix(NA, n, length(classes))

# LOOCV
for (i in 1:n) {
  train_idx <- setdiff(1:n, i)
  test_idx  <- i
  
  X_train <- X[train_idx, ]
  y_train <- y[train_idx]
  X_test  <- X[test_idx, , drop = FALSE]
  
  # --- Step 1: Fit PLS-DA on training data ---
  plsda_fit <- mixOmics::plsda(X_train, y_train, ncomp = 2)
  #plotIndiv(plsda_fit)
  
  # --- Training scores (first 2 components) ---
  train_scores <- plsda_fit$variates$X[, 1:2, drop = FALSE]
  
  # --- Test scores (first 2 components) ---
  test_pred <- predict(plsda_fit, X_test)
  # Depending on the version, this might be a list of length 1
  # Coerce to a matrix and select first 2 components
  #test_scores <- as.matrix(test_pred$variates$X)[, 1:2, drop = FALSE]
  
  # --- Step 2: Fit KNN on training projections ---
  knn_fit <- knn3(train_scores, y_train, k = 9)
  
  # --- Step 3: Predict held-out sample ---
  prob <- predict(knn_fit, test_pred$variates, type ='prob')
  probs_loocv[test_idx] <- prob[1]
  preds[test_idx] <- colnames(prob)[which.max(prob)]
}

# --- Results ---
# Misclassification error
class_err <- mean(preds != y)
cat("LOOCV Misclassification Error:", class_err, "\n")



# Confusion matrix
conf_mat <- confusionMatrix(preds, y)
print(conf_mat)
```

```{r, fig.height = 4, fig.width = 4}
roc<- roc(response = as.numeric(mclust_predicted$cond == "IPF"),
          predictor = probs_loocv[, 1], smooth = F)
roc


ggroc(list(IPF=roc#, nonIPF=roc_nonipf
), 
linewidth=0.75,legacy.axes = T)+
  theme_bw()+
  geom_abline(slope=1, intercept=0, lty = 2)+
  xlab("FPR")+
  ylab("TPR")+
  theme(
    # grid lines can be controversial, in my field it's not seen often
    panel.grid.minor=element_blank(), 
    panel.grid.major=element_blank(),
    axis.text = element_text(color="black",size=14), # default font size is too small
    axis.text.x = element_text(angle = 30, hjust = 1),
    axis.ticks = element_line(colour="black", linewidth = 1), # just plain old black please
    axis.title = element_text(size=14), # default font size is too small
    legend.title=element_text(size=14, vjust=0.5, hjust=0.5),
    legend.text=element_text(size=14, vjust=0.5, hjust=0),
    plot.margin=unit(c(1,1,1,1),"mm"),
    plot.background=element_rect(fill="transparent", colour=NA),
    panel.border = element_rect(colour="black", linewidth = 1), # I like to draw a crisp border
    panel.background=element_rect(fill="transparent", colour=NA),
    legend.background=element_rect(fill="transparent", colour=NA),
    legend.box.background=element_rect(fill="transparent", colour=NA),
    legend.key=element_rect(fill="transparent", colour=NA),
    legend.position = 'none')+
  scale_color_manual("Diagnosis",
                     values = c("#3c67a4"#,'maroon4'
                     ))+
  guides(
    colour = guide_legend(
      override.aes = list()
    )
  )+
  annotate("text", y = c(0.05), x=0.5, 
           label = c("AUC: 0.753"#, "AUC: 0.573"
           ),
           size = 5, hjust =0, color = c("#3c67a4"#,'maroon4'
           ))
```