---
title: "Fig 4f"
output: html_document
author: "Seung J. Kim (skim823@uwo.ca)"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
source("/Users/jk/Documents/Lab2/visium/r_analysis/ann_finest_level/401/5p_deseq2/pool_cond_niches_comparison/loop_dds.R")
```

```{r, fig.height = 15, fig.width = 7}
library(dplyr)
library(tibble)
library(purrr)
library(tidyr)
library(jsonlite)

all_svgs_by_niche <- fromJSON("/Users/jk/Documents/Lab2/visium/python_analysis/local_401/nmf/ann_finest_level/nfact12/json/niche_gene_overlap.json")
cor_test <- list()
rho <- list()
pvalue <- list()
label_expr <- list()
corr_plots <- list()
gene_index_table <- list()

for (niche in niches) {
  res_filtered <- res_list[[niche]]%>%
         as.data.frame() %>%
         rownames_to_column(var = "gene") %>%
         filter(!is.na(padj), padj < 0.05, log2FoldChange > 1) %>%
         arrange(padj)
  
  gene_index_table[[niche]] <- data.frame(gene = character(), median_index = numeric(), stringsAsFactors = FALSE)
  
  for (gene in res_filtered$gene) {
    indices <- c()  # reset for each gene
    
    for (cond in names(all_svgs_by_niche)) {
      for (library_id in names(all_svgs_by_niche[[cond]])) {
        # Check if 'Macro' niche exists in this library
        if (!niche %in% names(all_svgs_by_niche[[cond]][[library_id]])) next
        
        gene_vec <- all_svgs_by_niche[[cond]][[library_id]][[niche]]$gene
        idx <- which(gene_vec == gene)[1]  # get first match or NA
        
        indices <- c(indices, idx)  # collect
      }
    }
    
    # Compute median index across all libraries/conditions
    avg_idx <- exp(mean(log(indices),na.rm = TRUE)) #median(indices, na.rm = TRUE)
    
    # Append result to table
    gene_index_table[[niche]] <- rbind(gene_index_table[[niche]], data.frame(gene = gene, median_index = avg_idx))
  }
  
  gene_index_table[[niche]] <- gene_index_table[[niche]] %>%
    mutate(row = row_number())
  
  cor_test[[niche]] <- cor.test(gene_index_table[[niche]]$row, gene_index_table[[niche]]$median_index, method = "spearman", exact = FALSE)
  
  rho[[niche]] <- round(cor_test[[niche]]$estimate, 3)
  pvalue[[niche]] <- signif(cor_test[[niche]]$p.value, 3)
}

pvalue_adj <- as.list(signif(p.adjust(unlist(pvalue), method = "BH"),2))

for (niche in niches) {
  # Plot
  corr_plots[[niche]] <- ggplot(gene_index_table[[niche]], aes(x = row, y = median_index)) +
    geom_point(shape = 21, size = 3, colour = "grey75") +
    geom_smooth(method = "loess", se = TRUE, level = 0.99, color = "blue4", fill = "grey50", lwd = 1, alpha = 0.2, span = .7)+
    labs(title = niche)+ #x = "DEG rank", y = "SVG rank") +
    xlab("") + ylab("") +
    theme_minimal()  +
    theme(
      axis.ticks = element_line(colour = "black"),
      axis.line = element_line(linewidth = 0.2, colour = "black"),
      panel.border = element_rect(fill = "transparent", colour = "black"),
      text = element_text(size = 14, color = "black"),
      axis.text = element_text(size = 16, color = "black"),
      axis.text.x = element_text(size = 16, color = "black", angle = 30, hjust=1),
      #axis.text.y = element_blank(),
      plot.title = element_text(size = 16, color = "black"),
      plot.margin = unit(c(-2,0.5,-2,0), "mm"),
      plot.background = element_rect(fill = "transparent", colour = NA),
      panel.background = element_rect(fill = "transparent", colour = NA),
      panel.grid = element_blank(),
      legend.position = "none",
      aspect.ratio = 1
    ) + 
    ylim(0,3000)+
    annotate("text", x = 0, y = 2700, 
             #label = label_expr[[niche]],
             label = paste0("ρ==",bquote(.(rho[[niche]]))),
             parse = TRUE,
             size = 4.8,
             hjust = 0
    ) + 
    annotate("text", x = 0, y = 2200, 
             #label = label_expr[[niche]],
             label = paste0("FDR==",bquote(.(pvalue_adj[[niche]]))),
             parse = TRUE,
             size = 4.8,
             hjust = 0
    ) + 
    if (niche %in% c("Alv. FB/immune", "SMC", "Immune", "Adv. FB", "Alv. macro", "B")) {
      theme(axis.text.y = element_blank())
    }
}
  
corr_plotgrid <- plot_grid(
  plotlist = corr_plots[c('ATI/Endo', 'Alv. FB/immune', 'Plasma', 'SMC', 'ATII', 'Immune', 'Airway', 'Adv. FB', 'Perib. FB', 'Alv. macro', 'Macro', 'B')], ncol = 3, nrow = 4
) 
print(corr_plotgrid)

corr_patchwork <- patchwork::wrap_plots(
  corr_plots[c('ATI/Endo', 'Alv. FB/immune', 'Plasma', 'SMC', 'ATII', 'Immune', 'Airway', 'Adv. FB', 'Perib. FB', 'Alv. macro', 'Macro', 'B')], ncol = 2, nrow = 6, axis_titles = "collect"
) 
print(corr_patchwork)
dir.create("corr")

ggsave("corr/corr_plotgrid_ggsave.pdf", device = cairo_pdf, plot = corr_patchwork,  height = 15, width = 7, bg = "transparent")


```